### ISSUE TITLE
https://camunda.org/release/camunda-eclipse-plugin/update-sites/latest doesn't exist

### ISSUE THREAD

**Issue by SolarBilling** [camunda/camunda-docs-static#30]
This directory is referred to twice in the text and once in the image in 
https://docs.camunda.org/stable/guides/installation-guide/camunda-modeler/

latest should be a symbolic link to kepler.

**Comment by yanavasileva** [comment]
Hi @SolarBilling,

This link is from a quite old version of our documentation.
The eclipse plugin is no longer supported.

Please check the latest version which can be found here:
https://docs.camunda.org/manual/latest/installation/camunda-modeler/

Best regards,
Yana
